redis:
  image: redis
  ports:
    - "6379:6379"
web:
  build: .
  command: bin/rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/shortener
  ports:
    - "3000:3000"
  links:
    - redis:redis.local
  environment:
    REDIS_URL: redis://redis.local:6379
